-- Create DHBW table
CREATE TABLE "DHBW" (
    "LOCATION"      VARCHAR(30) NOT NULL PRIMARY KEY,
    "EMAIL-DOMAIN"  VARCHAR(30)
) 
GO

-- Create USER table
CREATE TABLE "USER" (
    "USER-ID"           INT IDENTITY(1000, 1) PRIMARY KEY,
    "FIRSTNAME"         VARCHAR(30) NOT NULL,
    "LASTNAME"          VARCHAR(30) NOT NULL,
    "DHBW"              VARCHAR(30) FOREIGN KEY REFERENCES [DHBW]("LOCATION"),
    "COURSE-ABR"        VARCHAR(15) NOT NULL,
    "COURSE"            VARCHAR(30) NOT NULL,
    "EMAIL"             VARCHAR(50) NOT NULL UNIQUE,
    "CITY"              VARCHAR(30),
    "BIO"               VARCHAR(1000),
    "RFID-ID"           VARCHAR(30) UNIQUE,
    "PW-HASH"           VARCHAR(30) UNIQUE NOT NULL,
    "IS-VERIFIED"       BIT NOT NULL DEFAULT 0,
    "VERIFICATION-ID"   INT NOT NULL,
    "TMS-CREATED"       DATETIME DEFAULT CURRENT_TIMESTAMP,
) 
GO

-- Create TAG table
CREATE TABLE "TAG" (
    "TAG-ID"        INT IDENTITY(1000, 1) PRIMARY KEY,
    "TAG"           VARCHAR(15) NOT NULL,
    "USER"          INT FOREIGN KEY REFERENCES [USER]("USER-ID"),
    "TMS-CREATED"   DATETIME DEFAULT CURRENT_TIMESTAMP
) 
GO

-- Create TAG-VALIDATION table
CREATE TABLE "TAG-VALIDATION" (
    "VALIDATION-ID" INT IDENTITY(1000, 1) PRIMARY KEY,
    "TAG"           INT FOREIGN KEY REFERENCES [TAG]("TAG-ID"),
    "VALIDATED-BY"  INT FOREIGN KEY REFERENCES [USER]("USER-ID"),
    "COMMENT"       VARCHAR(1000),
    "TMS-CREATED"   DATETIME DEFAULT CURRENT_TIMESTAMP
) 
GO

-- User view that excludes sensitive data like password hashes
CREATE VIEW [USERS-NOT-SENSITIVE] AS
SELECT [USER].[USER-ID],
       [USER].[FIRSTNAME],
       [USER].[LASTNAME],
       [USER].[DHBW],
       [USER].[COURSE-ABR],
       [USER].[COURSE],
       CONCAT([USER].[EMAIL], '@', [DHBW].[EMAIL-DOMAIN]) AS EMAIL,
       [USER].[CITY],
       [USER].[BIO],
       [USER].[IS-VERIFIED],
       [USER].[TMS-CREATED]
  FROM [dbo].[USER]
  INNER JOIN [DHBW] ON [USER].[DHBW] = [DHBW].[LOCATION]
  GO
 
